server:
    port: 8081
    servlet:
        context-path: /elaparato
spring:
    application:
        name: elaparato-service
    datasource:
        url: jdbc:mysql://localhost:3306/elaparato?serverTimezone=UTC
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/el-aparato-Franco-Leonardo
