server:
    port: 9090
spring:
    application:
        name: elaparato-gateway
    cloud:
        gateway:
            routes:
            -   id: elaparato
                predicates:
                - Path=/elaparato/**
                uri: http://localhost:8081
